baseURL = 'https://clubdefisicauab.cat/'
locale = 'ca'
title = 'Club de Física UAB'
theme = 'blowfish'
buildFuture = true

[params]
  logo = "logo.png"
  defaultAppearance = "light"
  autoSwitchAppearance = false
    favicon = "favicon.ico"
    # Si el tema busca aquestes mides, posa-les també
    favicon16 = "favicon-16x16.png"
    favicon32 = "favicon-32x32.png"
    appleTouchIcon = "apple-touch-icon.png"

[params.header]
  themeToggle = false
  showTitle = true

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "inici"
  name = "Inici"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "qui"
  name = "Qui Som"
  url = "/qui-som/"
  weight = 20

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 30

  [[menu.main]]
  identifier = "paperillos"
  name = "Paperillos"
  url = "/paperillos/"
  weight = 40

[[menu.main]]
  name = "Agenda"
  url = "/agenda/"
  weight = 50

[[menu.main]]
  identifier = "contacte"
  name = "Contacte"
  url = "/contacte/"
  weight = 60

[[menu.footer]]
  name = "Política de Privadesa"
  url = "/politica-privadesa/"
  weight = 10

paginate = 30

[params.article]
  showComments = true

[params.comments]
  enable = true
  provider = "giscus"

  [params.comments.giscus]
    repo = "clubfisicauab/cf-web" # Exemple: "ClubFisicaUAB/web"
    repoId = "R_kgDONi9X0g"           # Copiat de giscus.app
    category = "General"                     # La categoria de GitHub Discussions
    categoryId = "DIC_kwDONi9X0s4DAnhs"   # Copiat de giscus.app
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "light"
    lang = "ca"                              # Posa la interfície en català